<html>
    <head>
        <title>Index</title>
        <script type="text/javascript" language="javascript" src="public/js/funciones.js"></script>
    </head>
    <body onload="limpiar();">

        <h1>Agregar usuarios</h1>

        <form name="form" action="" method="post" enctype="multipart/form-data"> <!--el action vacio para que al dar submit llame a la misma pagina. -->
            Nombre: <input type="text" name="nom"><br/>
            Correo: <input type="text" name="correo"><br/>
            Login: <input type="text" name="login"><br/>
            Password: <input type="password" name="pass"><br/>
            Foto: <input type="file" name="foto"> (solo JPG)<br/>

            <input type="hidden" name="grabar" value="si">
            <a href="javascript:void(0)" onclick="document.form.submit();">Enviar</a>
        </form>

    </body>
</html>