<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>ERROR | Sistema SIAS</title>
    <link href="public/css/estilos1.css" rel="stylesheet" type="text/css" />
    <style type="text/css">
        a:link {
            text-decoration: none;
            color: #666666;
        }
        a:visited {
            text-decoration: none;
            color: #666666;
            font-size: 11px;
        }
        a:hover {
            text-decoration: none;
            color: #666666;
        }
        a:active {
            text-decoration: none;
            color: #666666;
        }
        -->
    </style>
</head>

<body>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<table width="720" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
        <td background="imagenes/enc_fondo.jpg" ><div align="center">
                <p>&nbsp;</p>
                <p>&nbsp;</p>
                <p><span class="AplicantesError">ERROR</span></p>
            </div></td>
    </tr>
</table>
<table cellpadding="0" cellspacing="0" width="720" border="0" align="center">
    <tr>
        <td width="8" bgcolor="#FFFFFF"></td>
        <td width="720" bgcolor="#FFFFFF" align="left"><table cellspacing="0" cellpadding="0" width="720" border="0">
                <tr height="19">
                    <td class="AplicantesControl"  background="images/cajas/fon2.gif" height="19"><div align="center" class="TextoObligatorio Estilo2">
                            <p>
                                <?php
                                if(isset($_SESSION['error']))

                                    echo $_SESSION['error'];
                                else
                                    echo "OTRO ERROR";

                                ?>
                            </p>
                            <p class="punto"><a href="index.php">volver</a> </p>
                        </div></td>
                </tr>
                <tr>
                    <td></td>
                </tr>
            </table>

        </td>
        <td width="8" bgcolor="#FFFFFF"></td>
    </tr>
</table>
<p>&nbsp;</p>
</body>
</html>
