<html>
<head>
    <title>Menu</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="stylesheet" type="text/css" href="public/css/estilos.css">
    <link rel="stylesheet" type="text/css" href="public/css/estiloMenu.css">
</head>

<body>
    <div id="menu_marco">
        <div id="menu_header">
            <?php include("view/xheader.phtml")?>
        </div>

        <div id="menu_contenido">

            <div id="menu_opciones">
                <?php include("view/xopciones.phtml");?>
            </div>

            <div id="menu_cuerpo">
                <img src="public/images/sistemaConceptual/principal.jpg" alt="" width="247" height="204" />
            </div>

            <div id="menu_usuario">
                <?php include("view/xusuario.phtml");?>
            </div>

        </div>
        <div id="menu_footer">
            <?php include("view/xfooter.phtml");?>
        </div>


    </div>



</body>
</html>