<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <style type="text/css">

        #header h1 {
            font-family: Verdana, Arial, Helvetica, sans-serif;
            font-size: 30px;
            color:#eeeeee;
            text-shadow: -1px -2px #cccccc;
            padding-right: 0px;
            padding-bottom: 0px;
            padding-left: 10px; }

        #header p{
            font-family: verdana;
            font-size: 20px;
            color: seashell;
        }

        #header h1, p {
            display: inline;
            vertical-align: bottom;
        }


    </style>
</head>
<body>



<div id="header">
    <h1>SIAS</h1>
    <p>Sistema de Informacion Adaptativo para el Analisis Social</p>
</div>

</body>
</html>