<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="stylesheet" type="text/css" href="public/css/estilos.css">
    <link rel="stylesheet" type="text/css" href="public/css/estiloMenu.css">
    <style type="text/css">

        #navlist a{
            text-decoration:none;
        }

        #navlist {
            background-color:#206A9B;
            margin:0px;
            padding:0px;
            font-family: Verdana, Arial, sans-serif;
            font-size: 15px;
            float: left;
            width: 170px;
            margin-top: 30px;
            margin-left: 5px;
        }
        #navlist ul {
            list-style: none;
        }

        #navlist li a{
            display: block;
            height: 25px;
            width: 100px;
            padding: 9px;
            margin: 5px;
            background: inherit;
            border-right: 4px solid #444;
            color: whitesmoke;
            text-transform: lowercase;
            font-size: 0.9em;
        }

        #navlist li a:hover {
            color: #f4f4f4;
            background: cadetblue;
            border-right: 4px solid gray;
        }

        #navlist li .active {
            color: #999;
            background: #333;
            border-right: 4px solid #444;
        }

    </style>
</head>
<body>

<div id="navlist">
<ul>
    <li><a href="<?php echo Conectar::ruta();?>?accion=index" title="Home">Home</a> </li>
    <li><a href="<?php echo Conectar::ruta();?>?accion=veruser" title="Ver usuarios">Ver usuarios</a> </li>
    <li><a href="<?php echo Conectar::ruta();?>?accion=adduser" title="Agregar usuarios">Agregar usuarios</a> </li>
    <li><a href="<?php echo Conectar::ruta();?>?accion=encuesta" title="Nueva encuesta">Nueva encuesta</a> </li>
    <li><a href="<?php echo Conectar::ruta();?>?accion=verEncuestas" title="Ver encuestas">Ver encuestas</a> </li>
</ul>
</div>


</body>
</html>