<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="stylesheet" type="text/css" href="public/css/estilos.css">
    <link rel="stylesheet" type="text/css" href="public/css/estiloMenu.css">

    <style type="text/css">

        #navlistito a{
            text-decoration:none;
        }

        #navlistito {
            background-color:#206A9B;
            margin:0px;
            /*padding:0px;*/
            font-family: Verdana, Arial, sans-serif;
            font-size: 15px;
            float: left;
            width: 120px;
            /*margin-top: 30px;*/
        }

        #navlistito p a{
            display: block;
            height: 25px;
            width: 100px;
            /*padding: 9px;*/
            /*margin: 5px;*/
            background: inherit;
            border-left: 4px solid #444;
            color: whitesmoke;
            text-transform: lowercase;
            font-size: 0.9em;
            padding-left: 0px;
        }

        #navlistito p a:hover {
            color: #f4f4f4;
            background: cadetblue;
            border-right: 4px solid gray;
        }

        #navlistito p .active {
            color: #999;
            background: #333;
            border-right: 4px solid #444;
        }

        #navlistito h3{
            color: white;
        }

        #navlistito img, h3, p, a{
            margin-left: 10px;
        }




    </style>
</head>
<body>

<div id="navlistito">
    <img src="public/fotos/<?php echo $_SESSION["foto"]?>.jpg" width="75" height="75">

        <h3><?php echo $_SESSION["foto"];?></h3>
        <p><a href="<?php echo Conectar::ruta();?>?accion=salir">Cerrar Sesion</a></p>

</div>




</body>
</html>